### ISSUE TITLE
dcoker run bug

### ISSUE THREAD

**Issue by lijianl** [bitcoin-sv/docker-sv#3]
************************
EXCEPTION: N5boost10filesystem16filesystem_errorE
boost::filesystem::create_directory: File exists: "/home/bitcoin/.bitcoin"
bitcoin in AppInit()

bitcoind: chainparamsbase.cpp:39: const CBaseChainParams& BaseParams(): Assertion `globalChainBaseParams' failed.

**Comment by Danconnolly** [comment]
duplicate of https://github.com/bitcoin-sv/docker-sv/issues/5
