### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by lijianl** [bitcoin-sv/docker-sv#4]
EXCEPTION: N5boost10filesystem16filesystem_errorE boost::filesystem::status: Function not implemented: "/home/bitcoin/.bitcoin" bitcoin in AppInit()

**Comment by lijianl** [comment]
does any body responsible for the issue

**Comment by Danconnolly** [comment]
Duplicate of https://github.com/bitcoin-sv/docker-sv/issues/5
