### ISSUE TITLE
bug5

### ISSUE THREAD

**Issue by lijianl** [bitcoin-sv/docker-sv#5]
EXCEPTION: N5boost10filesystem16filesystem_errorE boost::filesystem::create_directory: File exists: "/home/bitcoin/.bitcoin" bitcoin in AppInitRPC()

**Comment by CassClark** [comment]
@lijianl would you mind advising what OS you are using please? thanks

**Comment by lijianl** [comment]
Linux version 4.4.0-1109-aws (buildd@lgw01-amd64-017) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12) ) #120-Ubuntu SMP Fri Jun 5 01:26:57 UTC 2020

**Comment by lijianl** [comment]
why docker image can not separate the lib

**Comment by lijianl** [comment]
does any body responsible for the git issues

**Comment by Danconnolly** [comment]
I'm sorry but Ubuntu 16.04 is no longer supported. Please use a newer version of Ubuntu.

https://ubuntu.com/about/release-cycle
