### ISSUE TITLE
sync block stop at 706295

### ISSUE THREAD

**Issue by lijianl** [bitcoin-sv/docker-sv#6]
i was using docker-1.07.1 to sync bsv block-data and the syncing was stop at block 706295 for some days.

and there is no error to show in log ? what should i do ??????

```
### conf to bitcoin.conf
server=1
port=8333
rpcport=8332
rpcallowip=0.0.0.0/0
reindex=1
excessiveblocksize=10000000000
maxstackmemoryusageconsensus=200000000
maxmempool=2000
maxsigcachesize=250
maxscriptcachesize=250
maxconnections=7
mempoolexpiry=72
prune=600000
```

can i get any help from your guys

**Comment by CassClark** [comment]
Hi can I ask what your machine spec is please?   

The recommendation is: https://bitcoinsv.io/documentation/miners/system-requirements/

It's also worth noting that the latest version of the node software is v1.0.10, therefore it would be recommended that you upgrade if you haven't already: https://bitcoinsv.io/2021/11/25/upgrades-bsv-v1-0-10-mapi-v1-4-0/

**Comment by CassClark** [comment]
closing this issue due to time passed with no response.
