### ISSUE TITLE
docker image error

### ISSUE THREAD

**Issue by lijianl** [bitcoin-sv/docker-sv#8]
at first  run at local linux

1.   wget http://download.bitcoinsv.io/bitcoinsv/1.0.11/bitcoin-sv-1.0.11-x86_64-linux-gnu.tar.gz 
2.  `./bitcoind: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by ./bitcoind)`

i think that maybe lib errors, and then  i choose run with docker,
and change Dockerfile like this:
```
# change to ubuntu:latest  using  glibc-2.31
FROM ubuntu:latest
.....
RUN ldd --version  # to make sure glibc version upper 2.25  =>  ldd (Ubuntu GLIBC 2.31-0ubuntu9.7) 2.31
```

still met the same error when running docker container

```
************************
EXCEPTION: N5boost10filesystem16filesystem_errorE
boost::filesystem::create_directory: File exists: "/home/bitcoin/.bitcoin"
bitcoin in AppInit()

bitcoind: chainparamsbase.cpp:39: const CBaseChainParams& BaseParams(): Assertion `globalChainBaseParams' failed.
```

could you give some explantion for these,

**Comment by pfromberg** [comment]
I assume you have checked that /home/bitcoin/.bitcoin is indeed a directory and not a file. Also, are you still using Ubuntu 16.04? We do not support Ubuntu 16.04, not even as Docker host.
